name: License Scanning

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dotnet-modules-scan:
    name: dotnet-scan
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: 8.x
      - name: Build project with dotnet
        run: dotnet build --configuration Release
        working-directory: 'src'
      - name: Install nuget-license
        run: dotnet tool install --global nuget-license --version 3.1.3
        working-directory: 'src'
      - name: run nuget license
        run: nuget-license -i fdc3-dotnet.sln --allowed-license-types ../.license/allowed-licenses.json --output JsonPretty --error-only -exclude-projects ../.license/excluded-projects.json -mapping ../.license/license-mapping.json
        working-directory: 'src'
